### ISSUE TITLE
Linting reference shows functions, not magics

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/algoesup#15]
@densnow wrote "I am starting to think having the docs auto generated for the magic commands (i.e having a function signature which is not supposed to be called) could be misleading. Would you agree?"

Yes, that part of the library reference needs to be written by hand, or just [hide the signature](https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_signature) for those functions.

**Comment by densnow** [comment]
Made a couple of commits to fix typos, change Dockerfile and roll back version of package that was causing me issues. At the same time the option to hide the signature of the magic functions has been added to `library.md`

I think it looks OK, so probably this issue can be closed.

**Comment by mwermelinger** [comment]
Closed by 83628d4ceccb126b14a0f693b5f7f02712bcd235
