### ISSUE TITLE
"incomplete escape sequence" error for `%allowed` on Windows 

### ISSUE THREAD

**Issue by densnow** [dsa-ou/algoesup#16]
Using `%allowed` on Windows in Jupyter Notebook  prints the following error:
```text
Error on executing allowed  C:\Users\<username>\AppData\Local\Temp\tmppsw754ap.py:
incomplete escape \U at position 4
```
It's picking up the `\U` from `\Users` as an escape sequence. This appears to be a result of  setting the `shell=true` arg in `subprocess.run()`, and passing the command as a concatenated string which is directly interpreted by the shell (including escape sequences).

If we set `shell=false`, we can (Hopefully) bypass the shell, and instead of passing a concatenated string we should pass a *list* of args starting with the executable.

See [subprocesses - frequently used arguments](https://docs.python.org/3/library/subprocess.html#frequently-used-arguments) for reference.

**Comment by mwermelinger** [comment]
Thanks for spotting. If you fix it for Windows and test on Linux, I can then test on macOS.

**Comment by densnow** [comment]
Everything in the first comment is true and should be implemented, but it did not solve the issue. 

In the end I had to replace all instances of "\" with "/" in the temp file path. Windows can accept both as  path separators, iand AFAIK "\" are not allowed in filenames or directory names on Windows mac and Linux.
