### ISSUE TITLE
Include Google Colab

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/algoesup#24]
After closing #19:

- [x] guide for how to get started on Colab, share essay and comment on them
- [X] ~~share a Goole Drive folder with examples and templates?~~ (Edit: see below for how to open them directly from GH)
- [X] add `!pip algoesup allowed` at start of templates (with note it's for Google Colab) but without dependencies for `algoesup`
- [x] test that the examples & templates still work on Deepnote

**Comment by densnow** [comment]
On Colab one can select file->open notebook, then click the GitHub tab on the left. In the text-box that appears, paste the URL of this repo and all `.ipynb` files from the repo will be listed ready to open.

**Comment by mwermelinger** [comment]
Great, thanks! I guess the `!pip` should also be inserted at the start of the example essays, or do you have a better idea?

**Comment by densnow** [comment]
On a different note, not sure if this is necessary, but we can check if a notebook is running in Google colab by checking for a `COLAB_GPU` environment variable
```python
import os
if 'COLAB_GPU' in os.environ:
    !pip install algoesup --no-deps
    !pip install allowed ruff matplotlib
    ...
```
This might be useful, for example, if we wanted a single copy of the example essays for both DN and Colab without running the unnecessary pip installations each time in DN. Or even the templates, although it is less useful for those as one might as well delete the code if it is not being used.

**Comment by mwermelinger** [comment]
Brilliant! Just tried it out and  matplotlib isn't needed. Haven't yet tried on DN.

**Comment by mwermelinger** [comment]
I created a branch for this issue and added your code to the example and template essays. Could you do a 1-page 'getting started' for Colab? I guess the steps the user has to do are (in brief): 
1. Make sure you're logged in into your Google account and go to https://colab.research.google.com
2. Open our template directly from GitHub.
3. Copy to your Google Drive, rename it, and edit it.
4. Share essay, handle comments.

**Comment by densnow** [comment]
It seems a link can be generated that will open any publicly available notebooks on GitHub in Colab. E.g [https://colab.research.google.com/github/dsa-ou/algoesup/blob/main/src/docs/essays/template-data-structures.ipynb](https://colab.research.google.com/github/dsa-ou/algoesup/blob/main/src/docs/essays/template-data-structures.ipynb)

**Comment by mwermelinger** [comment]
Indeed, Peter Norvig's pytudes has links to cloud platforms for each of his notebooks. 

Not quite sure what you mean in the last sentence: to add buttons in the example essays page to open the examples and templates in Colab?

**Comment by densnow** [comment]
>Not quite sure what you mean in the last sentence: to add buttons in the example essays page to open the examples and templates in Colab?

In the getting started (Google Colab) guide, instead of asking the user to click **File->Open notebook** then clicking GitHub then entering the name of the repo, we can have colab open the individual notebooks by generating links as above. Maybe that is what you meant already!

**Comment by mwermelinger** [comment]
Not what I meant, but your suggestion is better.

**Comment by densnow** [comment]
I've pushed a draft of the "getting started  with Google Colab" guide to the `24-include-google-colab` branch. I have also run a couple of the example essays in DN with the additional code block without issue.

A link has been added to the new guide in `mkdocs.yml`, but I have not yet changed the landing page to mention Colab or link the guide.. I guess we can change the following

>f you prefer a 'Google Docs'-like environment for collaborative authoring and commenting on essays, we suggest Deepnote:

to say we suggest Deepnote and Colab, or maybe have separate points for each?

**Comment by mwermelinger** [comment]
Thanks. I've made some edits, mostly to shorten the text or shorten the lines to ease parsing diffs. 

You write that one addresses collaborators with +... but for me (Safari, macOS) it shows @...

Also, you write the shortcut is Ctrl+Shift+M but for the tooltips say Ctrl+Alt+M, although neither of works ie both shortcuts do nothing.
 
Were the above typos or is it really different on Linux?

**Comment by densnow** [comment]
@mwermelinger the section on comments is pasted straight from googles documentation.

**Comment by densnow** [comment]
Note to self: don't blindly trust documentation without testing, even if it is from Google!

There is a typo in Googles documentation: the shortcut to add a comment should be Ctrl+Alt+M, as you say. That combination worked for me in a notebook where I had commenting permissions, but it does *not* work in a notebook without those permissions (E.g. if I just clicked on one of the template links in the guide).

The +... does work for targeting collaborators email addresses, So does @. However, it looks like + is just an alias for @ in this context, so best just to mention the @
