### ISSUE TITLE
Allow further options for linters

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/algoesup#29]
The current approach with `IPython.core.magic_argument` is restrictive because it requires duplicating all the linter's options, otherwise there's a `UsageError`. For example, it's not currently possible to write `%allowed -m on` in case `pytype` is installed, or `%allowed -u 10 on` if one wants to check the current notebook only against units 1–10. (This is necessary for the M269 TMAs.)

A more flexible approach is to simply write `%<linter> on ...` and pass `...` to that linter. However, how to make sure that the default configuration (like `--ignore` for `ruff` or `-c` for `allowed`) is overwritten if the user specifies it?

Two approaches I can think of:
- Add an optional positional string argument for the options to pass to the linter, e.g. `%allowed -c tm112.json "-m -u 10" on`. It's a bit clunky to have some options in a string and others not (those we have defaults for). Maybe there's a way to not require a string, and just have zero or more extra arguments for the command?
- Do our own argument processing to permit `%linter [on [...]|off]`, by splitting the arguments string around spaces and checking if one of the options overrides a default option.

The first option is less work, especially if we can do it without needing double-quotes for the extra options.

**Comment by mwermelinger** [comment]
I prefer not to require the user to type more than needed. And since the args have hyphens themselves, will they be interpreted as unknown options, ie does `-a b` add `-a` and `b` to `baz`, or just `b`, or neither, with an error that `-a` is an unknown exception? I guess we'd have to experiment a bit...

**Comment by densnow** [comment]
Yes you are right, the dashes do not work.

Another option is ditch the `@magic_arguments` and `@argument` and instead use the `parse_known_args()` method from the regular `argparser` .

```python
@register_line_magic
def my_magic(line: str) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--config')
    parser.add_argument(
        "status",
        choices=["on", "off"],
        type=str.lower,
        help="Activate or deactivate the linter. If omitted, show the current status.",
        nargs="?",
        default=None,
    )
    known, unknown = parser.parse_known_args(line.split())
    print(f"Known args: {known}")
    print(f"Unknown args: {unknown}") 
```
```python
%my_magic on --config m269.json -b another_arg --unknown -s
```
```text
Known args: Namespace(config='m269.json', status='on')
Unknown args: ['-b', 'another_arg', '--unknown', '-s']

```

**Comment by mwermelinger** [comment]
I've pushed the changes to allow for extra command options, and updated the docs. For some reason, argparse can separate known and unknown arguments only if `on` is the first argument. So, `%allowed on -u 10` works but `%allowed -u 10 on` doesn't. I changed the docstrings for `on` to appear first.

Over to you to catch any command option errors. Thanks.

**Comment by densnow** [comment]
It seems `argparse` deems any arg added without a dash to be positional. This must be slightly different from the behaviour of the `@magic_arguments`

I've pushed the changes to handle better the errors caused from abnormal terminations from underlying linters. This mostly involves checking `CompletedProcess.stderr` for `ruff ` and `pytype`, but `allowed` prints errors to both, so this has been taken into account. 

It might be best for `allowed` to print messages from abnormal termination to `stderr` in the future to follow convention.

**Comment by densnow** [comment]
It looks like the `show_ruff_json` function was filtering out a depreciation warning related to the structure of the `ruff ` configuration in the pyproject.toml.

**Comment by mwermelinger** [comment]
Reopening this issue to allow @densnow to show both stderr and stdout, in case stderr has warnings. The message "{checker} didn't check code" must be changed.
