### ISSUE TITLE
`test` crashes on built-in functions

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/algoesup#45]
The `test` function uses `f.__code__.co_argcount` to find out how many arguments `f` has, but built-in functions don't have the `__code__` attribute and thus something like `test(sorted, [...])` crashes. This is a minor limitation as we usually don't test built-in functions. The solution is to 

- add to the documentation that built-in functions can't be tested

or

- find another way of determining the number of arguments, and preferably only the positional arguments

**Comment by densnow** [comment]
It looks like the `inspect` module could be a more robust way to do this  and in particular `inspect.signature`. I'll leave the link to [the documentation](https://docs.python.org/3.11/library/inspect.html#introspecting-callables-with-the-signature-object) here for now.

**Comment by mwermelinger** [comment]
Thanks, but the `inspect` documentation says that some CPython built-ins can't be handled either, so I'll just change the `test` docstring.
