### ISSUE TITLE
Transition from local `allowed` script to PyPi installation

### ISSUE THREAD

**Issue by densnow** [dsa-ou/algoesup#5]
Since allowed is now on the PyPi, it might be best to transition away from the local `allowed.py` script? The benefits include:
- Ease of installation
- dependency management
- no need to manually update script for changes
- one or two less files in the GH repo

For Deepnote we would need to update the `Dockerfile` and for Datalore we would need to update both `init.sh` and `environment.yml`. Furthermore, `algoesup.py` would need to be updated the most obvious part is  `checkers` dictionary but there could be more. 

There might be other changes required here, but I think I have covered the main ones.

**Comment by mwermelinger** [comment]
Good points. If you could test on DeepNote the PyPI version that would be good. (The current PyPI version can't handle folders, but that shouldn't be a problem in the context of DeepNote.)

**Comment by mwermelinger** [comment]
For the moment, we still need to keep the two JSON files because they add the `algoesup` imports.
